"""modelado inicial

Revision ID: 7e1a406e5b99
Revises: 
Create Date: 2026-07-03 11:49:02.404646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1a406e5b99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facultad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodo_academico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facultad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultad.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_estudios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidad.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_estudios_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('horas_teoria', sa.Integer(), nullable=False),
    sa.Column('horas_practica', sa.Integer(), nullable=False),
    sa.Column('semestre_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_estudios_id'], ['plan_estudios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_estudios_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_estudios_id'], ['plan_estudios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_prerequisito',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('prerequisito_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisito_id'], ['curso.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curso_id', 'prerequisito_id')
    )
    op.create_table('matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_academico_id', sa.Integer(), nullable=False),
    sa.Column('validado_user_id', sa.Integer(), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('comprobante_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_academico_id'], ['periodo_academico.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validado_user_id'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('periodo_academico_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('aforo', sa.Integer(), nullable=False),
    sa.Column('silabo_url', sa.String(length=255), nullable=True),
    sa.Column('acta_validada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_academico_id'], ['periodo_academico.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('qr_hash', sa.String(length=255), nullable=True),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('estado_curso', sa.String(length=50), nullable=False),
    sa.Column('promedio_final', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['matricula_id'], ['matricula.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_final', sa.Time(), nullable=False),
    sa.Column('aula', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('detalle_matricula_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['detalle_matricula_id'], ['detalle_matricula.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_evaluacion_id'], ['tipo_evaluacion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluacion')
    op.drop_table('tipo_evaluacion')
    op.drop_table('horario')
    op.drop_table('detalle_matricula')
    op.drop_table('solicitud_documento')
    op.drop_table('seccion')
    op.drop_table('matricula')
    op.drop_table('curso_prerequisito')
    op.drop_table('estudiante')
    op.drop_table('curso')
    op.drop_table('plan_estudios')
    op.drop_table('especialidad')
    op.drop_table('docente')
    op.drop_table('user')
    op.drop_table('periodo_academico')
    op.drop_table('facultad')
    # ### end Alembic commands ###
